file_cache_path "/var/chef-solo/cache/"
cookbook_path "/var/chef-solo/cache/cookbooks"
json_attribs "https://s3.amazonaws.com/kiputch-solo/nodejson/instanceid.json"
recipe_url "https://s3.amazonaws.com/kiputch-solo/cookbook/solo-all.tar.gz"
role_path "/var/chef-solo/roles"
checksum_path "/var/chef-solo/check-sum"
